class Memories:

    def __init__(self):
        self.memories = {
        2: "'At some point in our friendship, you let me know that you don't give people second chances easily. You told me that once a person becomes someone you would give a second chance to, they become like family to you. And you told me that I became someone you would give a second chance to. I will always remember that. I know you don't give that pass out lightly, so I will do my best to always be deserving of your trust, BUT BUT BUT, ALSO, that means that I have one get-out-of-jail pass with you and can betray you and you will be forced to give me a second chance. Your words, not mine :D HEHE JK ILY'",
        4: "'This one isn't really a memory, but I'm very grateful that you got me back into fashion. I kinda lost it during COVID, and found it really hard to recover from caring about what I look like. I am a big look-good-feel-good person, so thank you for getting me psyched about fashion again. Many people may think this is shallow, but I really care about presentation and I know you do too, so it means a lot to me. Your passion for style is actually very infectious and always inspires me to up my game, and I hope to be someone you can continue geeking out about fashion-related stuff to. It will also be great when you get famous and I can say you're my best friend :) #TEAMHERMES.'",
        6: "'I remember when you reassured me that I was smart & capable. I used to be insecure in my own intelligence and capabilities because I didn't know what I wanted to do, what kind of person I wanted to be, nor whether I even fit into this world the same way successful people do. COVID + countless rejections from girls definitely made this worse. But when I spoke to you about this in Modera (for some reason it was just you and me in the room, I don't remember where Alfred or Jerome were), you reassured me that I was able to get my USC club up and running because I was capable. You reassured me that my leadership style is different from others and that isn't a bad thing, and, more importantly, that all I needed to do was keep going and believe in myself. I don't know if that was the first time you've encouraged me like that (beyond my girl troubles), but that conversation really stuck with me, and I think about it every now and then when I'm feeling a bit lost.'",
        8: "'This one isn't really a memory, but I wanted to say that you are one of the best surprises in my life. Never in a million years did I think that Alfred would get a girlfriend before me given that I'm more of a social butterfly than he is, but I'm really glad that he did. I'm glad that he did because in a lot of ways I needed to see what a relationship truly is. Alfred taught me that chemistry between two people should not just be judged through the good times, and that the proper way to assess chemistry between two people is to evaluate how they get through tough times together. I genuinely believe he has that with you, and ever since you came into his life - and mine - I have learned that lesson over and over just by observing you two. Beyond that, you are a woman that I can truly call my friend; no other female bestfriend holds a candle to you, because you are a mother, a sister, and a friend all in one, and you're the only girl (outside of my own family) that I can call family.'",
        10: "'This one is kind of a non-memory, but over time, you really started to confide in me and I'm really glad that you did. I mean, you are still reserved in some ways with what you share and how you share it, but I'm grateful to have become someone you trust on the same level (if not more :P) as Cho, Susan, etc. I don't really remember the specifics of when exactly the transition happened, but it is actually a big honor that someone as mature as you - someone I look up to a lot - brought down her walls and let me in to her life. For the majority of my life, the definition of a proper best-friendship was specific to Alfred, but now I get to call you my best friend as well (please tell Alfred, if he's reading this, that he is still my number one), and expanded the definition for me. Thank you for that :)'",
        12: "'I remember all the little times where you looked out for me from the background and I had to hear about it from Alfred. Stuff like 'Oh we should get Aung Si something to eat too,' or 'Aung Si should try XYZ food'. Honestly that kind of awareness about someone you care about is something I explicitly learned from you. I'm usually chill with how I express my love for the people that I care about, and hope that the way I act around them inherently / subtly shows them that I care about them, but now I learned that tiny gestures like that can mean a whole lot to someone, and they build up to something bigger over time. Now, if I say similar things, like 'Oh we should do ABC for X person' to be thoughtful for them, know that I learned that from you, and I will continue to for the rest of my life!!!'"
        }
    
    def choose(self, n):
        words = self.memories[n].split()
        for i in range(len(words)):
            if i >= 13 and (i - 13) % 14 == 0:
                words[i] += '\n'
            else:
                words[i] += ' '
        words.append("\n")
        return ''.join(words)
